apiVersion: apps/v1
kind: Deployment
metadata:
  name: taint-toleration
  # these are replica set labels
  labels:
    purpose: toleration-demo
    project: roboshop
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      purpose: toleration-demo
      project: roboshop 
  # pod definition
  template:
    metadata:
      labels:
        # purpose: dp-demo
        purpose: toleration-demo
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx:latest